default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: brinsk_development

test:
  <<: *default
  database: brinsk_test

production:
  <<: *default
  database: brinsk_production
